### ISSUE TITLE
hi , I like your watch，could you tell me what is it's brand of the watch?

### ISSUE THREAD

**Issue by feiyan35488** [torvalds/libdivecomputer#1]
[the watch picture](http://www.improgrammer.net/wp-content/uploads/2015/12/Happy-Birthday-Linus-Torvalds-Turns-45.png) 

thanks very much

**Comment by TheRojam** [comment]
@feiyan35488 what the hack are you douing? o.O

**Comment by feiyan35488** [comment]
@TheRojam maybe I should ask him by email
